import Head from "next/head";
import Router from "next/router";
import { useEffect, useState} from "react";
import { css } from '@emotion/css';
import Link from "next/link";
import {container, body} from '../../styles/global'
import {csslistName, backcss,title,img_} from "../../styles/style-my-pokemon";


const MyPokemon =()=>{
    const [listMyPokemon, setListMyPokemon] = useState([])


    const getMypokemon =(e)=>{
        setListMyPokemon(e)
    }
    
    useEffect(()=>{
        const mypokemon = localStorage.getItem("catchUser");
        if(mypokemon){
            const srt = JSON.parse(mypokemon)
            getMypokemon(srt);
        }
    },[])

    return (
        <>
          <Head>
            <title>My List Pokemon</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
              <div className={container}>
              <div className={title}>
                <div onClick={() => Router.back()} className={backcss}>
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" />
                </svg>
                </div>
                 MY Pokemon
              </div>
              <div className={css`text-align: center;`}>
                  {listMyPokemon.length > 0 ? listMyPokemon.map((v)=>
                    <Link href={{pathname:`/pokemon-detail/${v.id}`, query: {name: v.name}}} key={v.name} >
                        <a className={csslistName}>
                            <img className={img_} src={v.img}  alt="" width={300} height={300} loading="eager"/>
                            <p>{ v.name}</p>
                        </a>
                    </Link>
                  ):
                  <div>Your Pockemon Empty</div>
                  }
                  </div>
              </div>
            </main>
        </>
    )
}

export default MyPokemon;