import Head from 'next/head'
// import Image from 'next/image'
import Link from 'next/link'
import { css } from '@emotion/css'
import {container, body} from '../styles/global'
import { useEffect, useState } from 'react'
import Router from "next/router";
import {csslistName, btnDiv, ar, desc,nextcss,mypokemoncss,dflex,dflex2,img_, overlay} from "../styles/style-home";
import {getdata} from '../pages/api/getGrapql'

const Home =({resp})=>{
  const [listPokemon, setListPokemon] = useState(resp.data.pokemons.results)
  const [loading, setLoading] = useState(false);
  const [limit, setLimit] = useState(20)
  const [ofset, setOfset] = useState(20)

  const NextShow = async() =>{
    setLoading(true)
    const resp = await getdata(limit, ofset)
    setListPokemon(resp.data.pokemons.results)
    document.querySelector('.scroll-here').scrollIntoView({behavior: "smooth", block: "start", inline: "nearest"});
    setLoading(false)
    setOfset(prevState => prevState+20)
  }
  const prevShow = async() =>{
    setLoading(true)
    const resp = await getdata(limit, ofset)
    setListPokemon(resp.data.pokemons.results)
    document.querySelector('.scroll-here').scrollIntoView({behavior: "smooth", block: "start", inline: "nearest"});
    setLoading(false)
    setOfset(prevState => prevState-20)
  }

  useEffect(()=>{
    
  },[])

  return (
    <>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={css`${container}`}>
          <div className={css`${dflex};@media (min-width: 600px) { padding: 0 6px;}`}>
            <h1 className='scroll-here'>
              List Pokemon 
            </h1>
            <span className={css`font-size: 20px;font-weight: 600;`}>Total : {resp.data.pokemons.count }</span>
          </div>

        {listPokemon.length && 
            <div className={dflex2}>
                {listPokemon.map((item, i) => 
                  <Link href={`/pokemon-detail/${item.name}`} key={i} >
                      <a className={css`${csslistName}`}>
                        <span className={css`font-size: 14px`}>#{item.id}</span>
                        {/* <img className={img_} src={imgPokemoan[i].img.dream_world.front_default}  alt="" width={300} height={300} loading="eager"/> */}
                        <img className={img_} src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/${item.id}.svg`}  alt="" width={300} height={300} loading="eager"/>
                          <p className={desc}>{ item.name}</p>
                      </a>
                  </Link>
                    )}
            </div>
          } 
        <div className={btnDiv}>
          <div className={nextcss}
              onClick={()=> prevShow()}> <span className={ar}><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" />
            </svg></span> Previous</div>
          <div className={nextcss}
              onClick={()=> NextShow()}>
                Next
                <span className={ar}>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7" />
                </svg>
                </span>
              </div>
        </div>
        <div  onClick={() => Router.push('/my-pokemon')} className={mypokemoncss}>My Pokemon List</div>
        </div>
      </main>
      {loading && <div className={overlay}><div></div></div>}
    </>
  )
}


Home.getInitialProps = async () => {
  const resp = await getdata(20, 0)
  return { resp }
}

export default Home;